#!/usr/bin/env python3
"""Bundle the current KH moth roster so the field Worker skips familiar taxa."""

import sqlite3
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DB_PATH = ROOT / "data" / "inat.db"
OUTPUT = ROOT / "field-alerts" / "src" / "known-moths.mjs"


def main():
    if not DB_PATH.exists():
        raise SystemExit(f"Database not found: {DB_PATH}")
    with sqlite3.connect(DB_PATH) as conn:
        ids = [row[0] for row in conn.execute(
            "SELECT taxon_id FROM moth_taxa ORDER BY taxon_id"
        )]
    lines = [
        "// Generated by scripts/build-known-moths.py; do not edit manually.",
        f"export const KNOWN_MOTH_IDS = new Set({ids!r});",
        "",
    ]
    OUTPUT.write_text("\n".join(lines), encoding="ascii")
    print(f"Wrote {len(ids)} known moth taxon IDs to {OUTPUT}")


if __name__ == "__main__":
    main()
